### ISSUE TITLE
[Keras example] Downloading data might conflict among parallel peers

### ISSUE THREAD

**Issue by marwage** [lsds/KungFu#199]

**Comment by lgarithm** [comment]
I think this might be a good use case for the barrier operator, e.g.

```python
if current_rank() == 0: # FIXME: use local rank
   download_if_not_exist()

run_barrier()
```

**Comment by marwage** [comment]
I was rerunning the my tf2_keras_mnist example, where I was deleting the dataset all the time, but I was not able to reproduce the error
