### ISSUE TITLE
bert demo question

### ISSUE THREAD

**Issue by rankeey** [lsds/KungFu#263]
@marwage 
I want to run bert elastic training with kungfu commit 9f8a69b, could tell me the corresponding bert commit number at kungfu branch which i can reproduce your result?

**Comment by marwage** [comment]
@rankeey I am verifying the result and will get back to you

**Comment by marwage** [comment]
@rankeey I verified my result with the schedule "16:1000,1:1000,16:1000,1:1000" and I got a f1-score of 74 in my run. The run in the past achieved a f1-score of 72.
In my run I used the state of the KungFu repo [v0.2.1](https://github.com/lsds/KungFu/tree/v0.2.1)
and the code of [BERT](https://github.com/marwage/bert/tree/kungfu)
The run script is [run.sh.txt](https://github.com/lsds/KungFu/files/4366259/run.sh.txt)
and the  [Dockerfile](https://github.com/marwage/bert/blob/kungfu/Dockerfile)
Let me know if it still does not work

**Comment by rankeey** [comment]
@marwage I can get a f1-score of 72.5.I think it is ok.Thanks.
Milo told me that you are testing the bert code with the kungfu master code. Have you done it?

**Comment by marwage** [comment]
@rankeey No worries! Yes I made that work as well. There is nothing specific about BERT.
