### ISSUE TITLE
After remove the worker from the cluster, it is better to set the rank id to -1.

### ISSUE THREAD

**Issue by rankeey** [lsds/KungFu#276]

**Comment by lgarithm** [comment]
After the worker is removed from the cluster, the APIs like `current_rank` and `current_cluster_size` shouldn't be called anymore. It is a bug that we don't throw exceptions when those APIs are called after worker removed.

**Comment by rankeey** [comment]
Throwing  exception is ok.

**Comment by luomai** [comment]
We have added a `detached` function to let worker check if it is still part of the cluster.
