### ISSUE TITLE
code loss

### ISSUE THREAD

**Issue by rankeey** [lsds/KungFu#348]
https://github.com/lsds/KungFu/blob/4ccc0f8fc0214519b3846052391f7bb8688ef502/srcs/cpp/include/kungfu/python/collective.h#L6
extern void kungfu_resize_from_url(char *p_changed, char *p_detached);

@lgarithm

**Comment by lgarithm** [comment]
what's wrong with this function?

**Comment by rankeey** [comment]
it will report  kungfu_resize_from_url not found， it seems you forgot to commit this change.
